name: Minecraft Server + Panel

on:
  workflow_dispatch:

jobs:
  minecraft:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      # Create docker-compose-playit.yml
      - name: Create Playit docker-compose file
        run: |
          cat <<'EOF' > docker-compose-playit.yml
          version: '3'
          services:
            playit:
              image: ghcr.io/playit-cloud/playit-agent:0.15
              restart: unless-stopped
              environment:
                - SECRET_KEY=${{ secrets.PLAYIT_SECRET }}
          EOF

      # Create docker-compose-panel.yml
      - name: Create Panel docker-compose file
        run: |
          cat <<'EOF' > docker-compose-panel.yml
          version: '3'
          services:
            crafty:
              image: registry.gitlab.com/crafty-controller/crafty-4:latest
              container_name: crafty
              restart: unless-stopped
              ports:
                - "8000:8000"
                - "8443:8443"
              volumes:
                - ./crafty/backups:/crafty/backups
                - ./crafty/logs:/crafty/logs
                - ./crafty/servers:/crafty/servers
                - ./crafty/config:/crafty/app/config
                - ./crafty/import:/crafty/import
          EOF

      # Run Playit
      - name: Start Playit
        run: docker compose -f docker-compose-playit.yml up -d

      # Run Panel
      - name: Start Panel
        run: docker compose -f docker-compose-panel.yml up -d

      - name: Show running containers
        run: docker ps -a
